# Generated by Django 5.1.6 on 2025-02-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0002_alter_job_category_alter_job_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
    ]
